### ISSUE TITLE
Key sequence l a c starts with non-prefix key l

### ISSUE THREAD

**Issue by xiaobing-huang** [tninja/aider.el#16]
Error happened while open a file:

> Debugger entered--Lisp error: (error "Key sequence l a c starts with non-prefix key l")
  #<subr define-key>((keymap (108 . hydra-gpt/body) (106 . hydra-jump/body) (118 keymap ... ... ... ... ... ...) (107 keymap ...) (116 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (115 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (114 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (113 keymap ... ... ... ... ... ... ... ... ... ... ... ...) (112 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (111 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (110 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (105 keymap ... ... ... ... ... ... ... ...) (103 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (102 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (99 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (98 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (9 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (13 . bookmark-jump) (32 . projectile-find-file) ...) "lac" aider-add-current-file)
  general-unbind-non-prefix-key(#<subr define-key> (keymap (108 . hydra-gpt/body) (106 . hydra-jump/body) (118 keymap ... ... ... ... ... ...) (107 keymap ...) (116 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (115 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (114 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (113 keymap ... ... ... ... ... ... ... ... ... ... ... ...) (112 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (111 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (110 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (105 keymap ... ... ... ... ... ... ... ...) (103 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (102 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (99 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (98 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (9 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (13 . bookmark-jump) (32 . projectile-find-file) ...) "lac" aider-add-current-file)
  apply(general-unbind-non-prefix-key #<subr define-key> ((keymap (108 . hydra-gpt/body) (106 . hydra-jump/body) (118 keymap ... ... ... ... ... ...) (107 keymap ...) (116 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (115 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (114 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (113 keymap ... ... ... ... ... ... ... ... ... ... ... ...) (112 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (111 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (110 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (105 keymap ... ... ... ... ... ... ... ...) (103 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (102 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (99 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (98 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (9 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (13 . bookmark-jump) (32 . projectile-find-file) (47 . +default/search-project) (42 . +default/search-project-for-symbol-at-point) (39 . vertico-repeat) (96 . evil-switch-to-windows-last-buffer) (60 . switch-to-buffer) (44 . persp-switch-to-buffer) ...) "lac" aider-add-current-file))
  define-key((keymap (108 . hydra-gpt/body) (106 . hydra-jump/body) (118 keymap ... ... ... ... ... ...) (107 keymap ...) (116 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (115 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (114 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (113 keymap ... ... ... ... ... ... ... ... ... ... ... ...) (112 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (111 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (110 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (105 keymap ... ... ... ... ... ... ... ...) (103 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (102 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (99 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (98 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (9 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (13 . bookmark-jump) (32 . projectile-find-file) ...) "lac" aider-add-current-file)
  (progn (progn (eval-after-load 'which-key #'(lambda nil (which-key-add-key-based-replacements (general--concat t doom-leader-key (general--concat t ... "")) "Add") (which-key-add-key-based-replacements (general--concat t doom-leader-alt-key (general--concat t ... "")) "Add") (which-key-add-key-based-replacements (general--concat t doom-leader-key (general--concat t ... "c")) "Current file") (which-key-add-key-based-replacements (general--concat t doom-leader-alt-key (general--concat t ... "c")) "Current file") (which-key-add-key-based-replacements (general--concat t doom-leader-key (general--concat t ... "w")) "Files in window") (which-key-add-key-based-replacements (general--concat t doom-leader-alt-key (general--concat t ... "w")) "Files in window") (which-key-add-key-based-replacements (general--concat t doom-leader-key (general--concat t ... "b")) "Batch direct marked files") (which-key-add-key-based-replacements (general--concat t doom-leader-alt-key (general--concat t ... "b")) "Batch direct marked files") (which-key-add-key-based-replacements (general--concat t doom-leader-key (general--concat t ... "g")) "Find files in repo") (which-key-add-key-based-replacements (general--concat t doom-leader-alt-key (general--concat t ... "g")) "Find files in repo") (which-key-add-key-based-replacements (general--concat t doom-leader-key (general--concat t ... "d")) "Open repo root") (which-key-add-key-based-replacements (general--concat t doom-leader-alt-key (general--concat t ... "d")) "Open repo root")))) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "a") "c")) #'aider-add-current-file) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "a") "w")) #'aider-add-files-in-current-window) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "a") "b")) #'aider-batch-add-dired-marked-files) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "a") "g")) #'aider-repo-find-name-dired) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "a") "d")) #'aider-git-repo-root-dired))
  (progn (progn (eval-after-load 'which-key #'(lambda nil (which-key-add-key-based-replacements ... "Aider") (which-key-add-key-based-replacements ... "Aider")))) (progn (progn (eval-after-load 'which-key #'(lambda nil ... ... ... ... ... ... ... ... ... ... ... ...))) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "a") "c")) #'aider-add-current-file) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "a") "w")) #'aider-add-files-in-current-window) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "a") "b")) #'aider-batch-add-dired-marked-files) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "a") "g")) #'aider-repo-find-name-dired) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "a") "d")) #'aider-git-repo-root-dired)) (progn (progn (eval-after-load 'which-key #'(lambda nil ... ... ... ... ... ...))) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "b") "b")) #'aider-switch-to-buffer) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "b") "c")) #'aider-clear)) (progn (progn (eval-after-load 'which-key #'(lambda nil ... ... ... ... ... ... ... ...))) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "s") "f")) #'aider-current-file-read-only) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "s") "l")) #'aider-send-line-under-cursor) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "s") "p")) #'aider-send-paragraph)) (progn (progn (eval-after-load 'which-key #'(lambda nil ... ... ... ... ... ... ... ...))) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "c") "c")) #'aider-code-change) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "c") "r")) #'aider-region-refactor) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "c") "u")) #'aider-undo-last-change)) (progn (progn (eval-after-load 'which-key #'(lambda nil ... ... ... ... ... ... ... ... ... ...))) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "d") "a")) #'aider-ask-question) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "d") "d")) #'aider-architect-discussion) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "d") "r")) #'aider-region-explain) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "d") "e")) #'aider-debug-exception)) (progn (progn (eval-after-load 'which-key #'(lambda nil ... ... ... ... ... ... ... ...))) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "z") "c")) #'aider-general-command) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "z") "h")) #'aider-help) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "z") "g")) #'aider-magit-show-last-commit)) (progn (progn (eval-after-load 'which-key #'(lambda nil ... ... ... ... ... ...))) (define-key doom-leader-map (general--kbd (general--concat t "l" "o")) #'aider-run-aider) (define-key doom-leader-map (general--kbd (general--concat t "l" "r")) #'aider-reset) (define-key doom-leader-map (general--kbd (general--concat t "l" "x")) #'aider-exit)))
  (progn (progn (progn (eval-after-load 'which-key #'(lambda nil (which-key-add-key-based-replacements ... "Aider") (which-key-add-key-based-replacements ... "Aider")))) (progn (progn (eval-after-load 'which-key #'(lambda nil ... ... ... ... ... ... ... ... ... ... ... ...))) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "a") "c")) #'aider-add-current-file) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "a") "w")) #'aider-add-files-in-current-window) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "a") "b")) #'aider-batch-add-dired-marked-files) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "a") "g")) #'aider-repo-find-name-dired) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "a") "d")) #'aider-git-repo-root-dired)) (progn (progn (eval-after-load 'which-key #'(lambda nil ... ... ... ... ... ...))) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "b") "b")) #'aider-switch-to-buffer) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "b") "c")) #'aider-clear)) (progn (progn (eval-after-load 'which-key #'(lambda nil ... ... ... ... ... ... ... ...))) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "s") "f")) #'aider-current-file-read-only) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "s") "l")) #'aider-send-line-under-cursor) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "s") "p")) #'aider-send-paragraph)) (progn (progn (eval-after-load 'which-key #'(lambda nil ... ... ... ... ... ... ... ...))) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "c") "c")) #'aider-code-change) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "c") "r")) #'aider-region-refactor) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "c") "u")) #'aider-undo-last-change)) (progn (progn (eval-after-load 'which-key #'(lambda nil ... ... ... ... ... ... ... ... ... ...))) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "d") "a")) #'aider-ask-question) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "d") "d")) #'aider-architect-discussion) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "d") "r")) #'aider-region-explain) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "d") "e")) #'aider-debug-exception)) (progn (progn (eval-after-load 'which-key #'(lambda nil ... ... ... ... ... ... ... ...))) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "z") "c")) #'aider-general-command) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "z") "h")) #'aider-help) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "z") "g")) #'aider-magit-show-last-commit)) (progn (progn (eval-after-load 'which-key #'(lambda nil ... ... ... ... ... ...))) (define-key doom-leader-map (general--kbd (general--concat t "l" "o")) #'aider-run-aider) (define-key doom-leader-map (general--kbd (general--concat t "l" "r")) #'aider-reset) (define-key doom-leader-map (general--kbd (general--concat t "l" "x")) #'aider-exit))))
  (if (and (featurep 'doom-keybinds) (vc-backend (or (buffer-file-name) default-directory))) (progn (progn (progn (eval-after-load 'which-key #'(lambda nil (which-key-add-key-based-replacements ... "Aider") (which-key-add-key-based-replacements ... "Aider")))) (progn (progn (eval-after-load 'which-key #'(lambda nil ... ... ... ... ... ... ... ... ... ... ... ...))) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "a") "c")) #'aider-add-current-file) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "a") "w")) #'aider-add-files-in-current-window) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "a") "b")) #'aider-batch-add-dired-marked-files) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "a") "g")) #'aider-repo-find-name-dired) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "a") "d")) #'aider-git-repo-root-dired)) (progn (progn (eval-after-load 'which-key #'(lambda nil ... ... ... ... ... ...))) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "b") "b")) #'aider-switch-to-buffer) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "b") "c")) #'aider-clear)) (progn (progn (eval-after-load 'which-key #'(lambda nil ... ... ... ... ... ... ... ...))) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "s") "f")) #'aider-current-file-read-only) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "s") "l")) #'aider-send-line-under-cursor) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "s") "p")) #'aider-send-paragraph)) (progn (progn (eval-after-load 'which-key #'(lambda nil ... ... ... ... ... ... ... ...))) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "c") "c")) #'aider-code-change) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "c") "r")) #'aider-region-refactor) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "c") "u")) #'aider-undo-last-change)) (progn (progn (eval-after-load 'which-key #'(lambda nil ... ... ... ... ... ... ... ... ... ...))) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "d") "a")) #'aider-ask-question) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "d") "d")) #'aider-architect-discussion) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "d") "r")) #'aider-region-explain) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "d") "e")) #'aider-debug-exception)) (progn (progn (eval-after-load 'which-key #'(lambda nil ... ... ... ... ... ... ... ...))) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "z") "c")) #'aider-general-command) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "z") "h")) #'aider-help) (define-key doom-leader-map (general--kbd (general--concat t (general--concat t "l" "z") "g")) #'aider-magit-show-last-commit)) (progn (progn (eval-after-load 'which-key #'(lambda nil ... ... ... ... ... ...))) (define-key doom-leader-map (general--kbd (general--concat t "l" "o")) #'aider-run-aider) (define-key doom-leader-map (general--kbd (general--concat t "l" "r")) #'aider-reset) (define-key doom-leader-map (general--kbd (general--concat t "l" "x")) #'aider-exit)))))
  aider-doom-setup-keys()
  run-hooks(change-major-mode-after-body-hook after-change-major-mode-hook)
  normal-mode(t)
  #<subr after-find-file>(nil t nil nil nil)
  apply(#<subr after-find-file> (nil t))
  (progn (fset #'sit-for #'ignore) (apply fn args))
  (unwind-protect (progn (fset #'sit-for #'ignore) (apply fn args)) (fset #'sit-for old))
  (let* ((old (symbol-function #'sit-for))) (unwind-protect (progn (fset #'sit-for #'ignore) (apply fn args)) (fset #'sit-for old)))
  doom--shut-up-autosave-a(#<subr after-find-file> nil t)
  apply(doom--shut-up-autosave-a #<subr after-find-file> (nil t))
  #f(advice doom--shut-up-autosave-a :around #<subr after-find-file>)(nil t)

**Comment by RomeoV** [comment]
I am still running into this issue. Why is it closed?
For me, it's 
```elisp
Debugger entered--Lisp error: (error "Key sequence l b b starts with non-prefix key l b")
```

**Comment by RomeoV** [comment]
I belive it clashes with the doom emacs `collab` keybindings...

**Comment by tninja** [comment]
@RomeoV does that mean update this line will resolve the issue? https://github.com/tninja/aider.el/blob/main/aider-doom.el#L24

(Not quite familiar with doom emacs, would be great to let me know how to fix this, Thanks.)

**Comment by RomeoV** [comment]
I'll look at your link tomorrow. But mostly the "issue" is just that both this package and the doom emacs "collab" config set map keys starting with `<leader> l`, but with different settings.
For doom users, they will be fine for now just commenting out the `collab` feature in their `init.el` file.
Perhaps this package could have a flag whether to use the proposed keymaps or not.

**Comment by RomeoV** [comment]
This is where doom defines the keymap:

https://github.com/doomemacs/doomemacs/blob/6a8c09f01288f1ed00a7cc2b7f5887e8f2b4be77/modules/config/default/%2Bevil-bindings.el#L584-L587

Specifically e.g.
```elisp
      (:when (modulep! :tools collab)
       (:prefix-map ("l" . "live share/collab")
        :desc "Switch to a shared buffer"      "b"   #'crdt-switch-to-buffer
        :desc "Connect to a session"           "c"   #'crdt-connect
```

Now, compared to the config for doom in this package
```elisp
  (when (and (featurep 'doom-keybinds)
             (vc-backend (or (buffer-file-name) default-directory)))
    (map! :leader
          (:prefix ("l" . "Aider")
                   (:prefix ("a" . "Add")
                    :desc "Current file" "c" #'aider-add-current-file
                    :desc "Files in window" "w" #'aider-add-files-in-current-window
                    :desc "Batch direct marked files" "b" #'aider-batch-add-dired-marked-files
                    :desc "Find files in repo" "g" #'aider-repo-find-name-dired
                    :desc "Open repo root" "d" #'aider-git-repo-root-dired)

                   (:prefix ("b" . "Buffer")
                    :desc "Switch to Aider" "b" #'aider-switch-to-buffer
                    :desc "Clear Aider" "c" #'aider-clear)
```

We can see that the root issue occurs when the doom `collab` option is enabled (and `evil` mode), the prefix-map `l` is created, with some keybindings. Then the aider package creates the `prefix` `l` with a different name and bindings.

Btw, here's what the help string of `map!` says about `:prefix` vs `:prefix-map`:
```raw
  :prefix [PREFIX] [...]          set keybind prefix for following keys. PREFIX
                                  can be a cons cell: (PREFIX . DESCRIPTION)
  :prefix-map [PREFIX] [...]      same as :prefix, but defines a prefix keymap
                                  where the following keys will be bound. DO NOT
                                  USE THIS IN YOUR PRIVATE CONFIG.
``` 
I'm not quite sure whether to use a `prefix` or `prefix-map` here and what the implications are.
But as of now, the problem is just that both `aider` and the `collab` doom config define a prefix for `:leader l`.

**Comment by RomeoV** [comment]
Ok I think I've figured out the solution.
We should be using `prefix-map` instead of `prefix` in this package, will will then create a new variable `doom-leader-Aider-map`, which we can use to rebind to a different key.

For example, we can remap the keymap to
```elisp
;; Start by unmapping the conflicting leader key from both `collab` and `aider`
(map! :leader "l" nil)
;; Now reassign properly to different keys
(map! :leader "L" doom-leader-Aider-map)
(map! :leader "L" doom-leader-collab-map)
```

**Comment by tninja** [comment]
@RomeoV Thanks for checking into the issue. Wonder if changing the leader key of this package to some other key will resolve the conflict? Eg. key "a"? or key "L"? If the new key have no conflict, it might be quick and easy change.

 I am not using doom emacs, would be great to get some suggestion. Thanks

**Comment by tninja** [comment]
just talked with aider and he told me that "collab" is an optional module. Seems that not all DOOM emacs user will hit the issue. aider also suggest to use "A" if there is a key conflict ("a" has already been taken for application given his feedback)

**Comment by RomeoV** [comment]
Yes that's right. Using prefix "A" would probably work.

**Comment by tninja** [comment]
Fixed in https://github.com/tninja/aider.el/pull/20

**Comment by tninja** [comment]
Close this issue since lead key has been changed to "A"
