### ISSUE TITLE
How to turn off autocommits

### ISSUE THREAD

**Issue by betaprior** [tninja/aider.el#24]
In a lot of cases, the autocommit feature can be a major nuisance / UX nightmare. How does one turn it off?

**Comment by tninja** [comment]
aider have a start parameter:  --no-auto-commits. You can defined it through aider-args variable

**Comment by tninja** [comment]
or you want to use the architect command / menu item to discuss with it firstly. If the change solution looks good. accept it with yes and it will make change commit

**Comment by rgalaxy** [comment]
I don't know, can we put this as config on `aider.conf.yaml`? do we need to put it as arguments instead?

**Comment by jackytank** [comment]
you guys could turn auto commit feature for every task done by setting this to false in your global `.aider.conf.yml` 
```yaml
model: <bla bla bla>
auto-commits: false
```
