### ISSUE TITLE
aider-add-current-file does not work over TRAMP

### ISSUE THREAD

**Issue by artyom-smushkov** [tninja/aider.el#36]
If project runs inside docker/podman container and is accessed in emacs via TRAMP `aider-add-current-file` function tries to add file using path with TRAMP prefix (like `/docker:container_name:/path/to/file`) which aider knows nothing about.

**Comment by tninja** [comment]
yeah I thought aider should only be able to add files in the same filesystem where aider start. Do you start aider inside docker / podman? If that is the case, I guess current implementation of aider.el will also need to start there.

**Comment by artyom-smushkov** [comment]
Yeah, I installed aider to the same docker container. Starting GUI program such as emacs there would be much trickier though. I believe "untrampifing" file paths should be as simple as wrapping them with file-local-name like this `(file-local-name (expand-file-name buffer-file-name))` Other then that aider.el seems to communicate with aider successfully.

**Comment by tninja** [comment]
I see. Yes installing GUI version of emacs could be a issue inside container. But no-x version of emacs installation should be fine based on my experience. It won't depend on GUI libraries and can work directly on terminal. I can even port all my .emacs.d there and it works fine.

**Comment by artyom-smushkov** [comment]
Sure it will work but using inferior version of Emacs for development (which is the main purpose) and normal one for everything else is not a good experience. I briefly checked aider with this small change added to my `init.el` and overall aider seems to work perfectly fine:
```lisp
    (defun aider-add-or-read-current-file (command-prefix)
      "Send the command \"COMMAND-PREFIX <current buffer file full path>\" to the corresponding aider comint buffer."
      ;; Ensure the current buffer is associated with a file
      (if (not buffer-file-name)
        (message "Current buffer is not associated with a file.")
        (let ((command (format "%s %s" (aider--get-add-command-prefix) (file-local-name (expand-file-name buffer-file-name)))))
        ;; Use the shared helper function to send the command
        (aider--send-command command))))
```
Just adding `file-local-name` does fix the issue.

**Comment by tninja** [comment]
Thanks for the solution! Great the change is small. Will check the backward compatibility, if it is good, will merge this change.

**Comment by artyom-smushkov** [comment]
Thanks for an awesome package!
