### ISSUE TITLE
read-only command does not work

### ISSUE THREAD

**Issue by LukeMauldin** [tninja/aider.el#40]
When using the command `aider-current-file-read-only` (`SPC A a f` in Doom Emacs), the file is added to the chat in write mode.

version: GNU Emacs 29.4 (build 2, aarch64-apple-darwin24.2.0, NS appkit-2575.30 Version 15.2 (Build 24C101)) of 2024-12-12

<img width="1139" alt="image" src="https://github.com/user-attachments/assets/0c4d8158-8d4e-4a8d-9947-893cbc7bfc15" />

**Comment by LukeMauldin** [comment]
Should be resolved in https://github.com/tninja/aider.el/pull/41

**Comment by tninja** [comment]
Thanks for finding the issue. Just merged the change

**Comment by tninja** [comment]
I am wondering if it is useful to have a toggle function for aider--add-file-read-only, in doom menu. if that function got triggered, reverse the variable name and show it in mini buffer with message function, to make it easier to change that in doom. right now transient menu already have it, toggle through @ key
if it is useful, maybe we can do it in future.

**Comment by LukeMauldin** [comment]
That could be useful but I think that we can clsoe this issue for now.
